server:
  port: 8081

spring:
  application:
    name: Inventory Management API

  datasource:
    url: ${DB_URL}
#    jdbc:postgresql://localhost:5433/db_inventorymanagement
    username: ${DB_USERNAME}
#    postgres
    password: ${DB_PASSWORD}
#      kuvmG2dSTdV0oJ3aJxGA0POiSweGJjEtrCtz5upK822ndYJfBFcKw6ntb1QT4FN9
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.PostgreSQLDialect

  Jackson:
    serialization:
      fail-on-empty-beans: false